/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.riosaputra.tugasuasoop;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class TaskManagement extends javax.swing.JFrame {

    /**
     * Creates new form TaskManagement
     */
    public TaskManagement() {
        initComponents();
    }
    
    public String wrapText(String passedStr)
    {
       
       
        final short LINE_LENGTH = 80;

       
        int nextCR = LINE_LENGTH;

       
        StringBuffer newStr = new StringBuffer(passedStr);

        
        for (int i = 0; i < newStr.length(); i++)
        {
                
                if (newStr.charAt(i) == '\n' || newStr.charAt(i) == '\r')
                        nextCR = i + LINE_LENGTH;

                
                if (newStr.charAt(i) == ' ' && i >= nextCR)
                {
                        newStr.insert((i + 1), "\n");
                        nextCR += LINE_LENGTH;
                }
        }

        return newStr.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roleGrup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        radioManager = new javax.swing.JRadioButton();
        radioProgrammer = new javax.swing.JRadioButton();
        radioUIDesign = new javax.swing.JRadioButton();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("Aplikasi Management System");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("pilih pekerjaan anda"));

        roleGrup.add(radioManager);
        radioManager.setText("Manager");

        roleGrup.add(radioProgrammer);
        radioProgrammer.setText("Programmer");

        roleGrup.add(radioUIDesign);
        radioUIDesign.setText("UIDesigner");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radioUIDesign, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioProgrammer, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioManager, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnSubmit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(radioManager)
                .addGap(18, 18, 18)
                .addComponent(radioProgrammer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioUIDesign)
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
         Manager manager = new Manager();
        manager.setId("12345");
        manager.setNama("Rio Saputra");
        manager.setJabatan("Manager Project");
        
        Programmer programmer = new Programmer();
        programmer.setId("234234");
        programmer.setNama("Wahyu Rahayu");
        programmer.setPekerjaan("Desktop Programmer");
        
        UIDesigner UIDesign = new UIDesigner();
        UIDesign.setId("333444");
        UIDesign.setNama("Riki Ardian");
        UIDesign.setPekerjaan("Front-end Designer");
        
        if (radioManager.isSelected()) {
            manager.mTask.setTask("Merencanakan Proyek sesuai Tujuan Perusahaan");
            manager.mTask.setDeskripsi("Seorang project manager harus menyiapkan strategi untuk menyelesaikan proyek dalam batas waktu tertentu sesingkat mungkin. Oleh karena itu, kamu bertanggung jawab untuk menemukan cara tercepat dengan manajemen sebaik mungkin untuk mencapai tujuan yang diinginkan stakeholder.");
            JOptionPane.showMessageDialog(
                null,
                    wrapText(manager.perkenalan() + "\n" + manager.pekerjaan())
            );
        } else if (radioProgrammer.isSelected()) {
            programmer.mTask.setTask("Mengkoding aplikasi management project");
            programmer.mTask.setDeskripsi("Menuliskan kode program atau coding menggunakan bahasa Java");
            JOptionPane.showMessageDialog(
                null,
                    wrapText(programmer.perkenalan() + "\n" + programmer.pekerjaan())
            );
        } else if (radioUIDesign.isSelected()) {
            UIDesign.mTask.setTask("Membuat UI aplikasi management project");
            UIDesign.mTask.setDeskripsi("Membuat design menggunakan Figma mengenai tampilan dari software");
            JOptionPane.showMessageDialog(null,
                    wrapText(UIDesign.perkenalan() + "\n" + UIDesign.pekerjaan())
            );
        }
                                            
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaskManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioManager;
    private javax.swing.JRadioButton radioProgrammer;
    private javax.swing.JRadioButton radioUIDesign;
    private javax.swing.ButtonGroup roleGrup;
    // End of variables declaration//GEN-END:variables
}
